name: conferenceapp
description: Flutter Europe conference app

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.6.2
  pedantic: ^1.8.0+1
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_messaging: ^5.1.6
  flutter_bloc: ^1.0.0
  intl: ^0.16.0
  bloc: ^1.0.0
  line_icons: ^0.2.0
  dynamic_theme: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

flutter:

  uses-material-design: true

  assets:
   - assets/flare/
   - assets/


  fonts:
    - family: PTSans
      fonts:
        - asset: assets/PT_Sans/PTSans-Bold.ttf
          weight: 600
        - asset: assets/PT_Sans/PTSans-Regular.ttf
          weight: 400
        - asset: assets/PT_Sans/PTSans-Italic.ttf
          # weight: 500
        - asset: assets/PT_Sans/PTSans-BoldItalic.ttf
          # weight: 600