name: conferenceapp
description: Flutter Europe conference app

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.6.2
  pedantic: ^1.8.0+1
  firebase_core: ^0.4.1+5
  firebase_analytics: ^5.0.6
  firebase_messaging: ^5.1.8
  firebase_auth: ^0.15.0
  firebase_ml_vision: ^0.9.2+2
  firebase_crashlytics: ^0.1.1+2
  firebase_performance: ^0.3.1+2
  camera: ^0.5.6+3
  cloud_firestore: ^0.12.9+5
  flutter_bloc: ^2.0.0
  bloc: ^2.0.0
  intl: ^0.16.0
  line_icons: ^0.2.0
  dynamic_theme: ^1.0.1
  extended_image: ^0.6.4
  json_serializable: ^3.2.2
  fluttertoast: ^3.1.3
  qr_flutter: ^3.1.0
  flutter_custom_clippers: ^1.1.0
  url_launcher: ^5.2.5
  share: ^0.6.3+1
  shared_preferences: ^0.5.4+5
  equatable: ^1.0.0
  collection: ^1.14.11
  provider: ^3.1.0+1
  package_info: ^0.4.0+10

  cupertino_icons: ^0.1.2

dependency_overrides:
  extended_image_library:
    git:
        url: https://github.com/fluttercandies/extended_image_library.git
        ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  build_runner:
  mockito:

flutter:
  uses-material-design: true

  assets:
   - assets/flare/
   - assets/

  fonts:
    - family: PTSans
      fonts:
        - asset: assets/PT_Sans/PTSans-Bold.ttf
          weight: 600
        - asset: assets/PT_Sans/PTSans-Regular.ttf
          weight: 400
        - asset: assets/PT_Sans/PTSans-Italic.ttf
          # weight: 500
        - asset: assets/PT_Sans/PTSans-BoldItalic.ttf
          # weight: 600