name: conferenceapp
description: Flutter Europe conference app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.8.1
  pedantic: ^1.8.0+1
  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  firebase_messaging: ^5.1.8
  firebase_auth: ^0.15.2
  firebase_ml_vision: ^0.9.3+3
  firebase_crashlytics: ^0.1.2+3
  firebase_performance: ^0.3.1+2
  firebase_remote_config: ^0.3.0
  camera: ^0.5.7+2
  cloud_firestore: ^0.12.11
  bloc: ^2.0.0
  flutter_bloc: ^2.1.1
  provider: ^3.2.0
  equatable: ^1.0.1
  intl: ^0.16.0
  line_icons: ^0.2.0
  dynamic_theme: ^1.0.1
  extended_image: ^0.6.8
  json_serializable: ^3.2.3
  fluttertoast: ^3.1.3
  qr_flutter: ^3.1.0
  flutter_custom_clippers: ^1.1.0
  url_launcher: ^5.2.7
  share: ^0.6.3+1
  shared_preferences: ^0.5.4+5
  collection: ^1.14.11
  package_info: ^0.4.0+10
  dotted_border: ^1.0.3
  characters: ^0.5.0
  hydrated_bloc: ^2.0.0
  http: ^0.12.0+2
  contentful: ^1.1.3
  contentful_rich_text: ^0.1.2
  rxdart: ^0.22.6
  expandable: ^4.0.1
  smooth_star_rating: ^1.0.3
  feature_discovery: ^0.6.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  build_runner:
  mockito:

flutter:
  uses-material-design: true

  assets:
   - assets/flare/
   - assets/

  fonts:
    - family: PTSans
      fonts:
        - asset: assets/PT_Sans/PTSans-Bold.ttf
          weight: 600
        - asset: assets/PT_Sans/PTSans-Regular.ttf
          weight: 400
        - asset: assets/PT_Sans/PTSans-Italic.ttf
          # weight: 500
        - asset: assets/PT_Sans/PTSans-BoldItalic.ttf
          # weight: 600